#!/bin/bash

WHERE=$HOME/where/projects/are\ at/
DOMAIN=$1
FROM=$WHERE$DOMAIN/

case $DOMAIN in
	sgs ) TO=username@host.com:public_html/
		;;
	  * ) echo "Bad Command"
		;;
esac

if [[ ! -z "$TO" ]]; 
then
	rsync -rvuz --exclude-from=.rsyncignore "$FROM" "$TO"
fi

