#!/bin/sh


ACTION=$1
WHERE=$HOME/Dropbox/clients/
DOMAIN=$2
DOMAINPATH=$WHERE$DOMAIN/site


if [ ! -z $ACTION ] && [ $ACTION == "-d" ]
then
    if [ -z $DOMAIN ] || [ ! -d "$DOMAINPATH" ]
    then
    	echo ""
    	echo "Please provide a domain name."
    	echo "Usage: "
    	exit 0
    elif [ ! -z $3 ] && [ $3 == "-l" ]
    then
        H_PATTERN=local_db_host
        U_PATTERN=local_db_user
        P_PATTERN=local_db_password
        N_PATTERN=local_db_name
        URL_PATTERN=local_site_url

    elif [ ! -z $3 ] && [ $3 == "-s" ]
    then
        H_PATTERN=staging_db_host
        U_PATTERN=staging_db_user
        P_PATTERN=staging_db_password
        N_PATTERN=staging_db_name
        URL_PATTERN=staging_site_url

    elif [ ! -z $3 ] && [ $3 == "-p" ]
    then
        H_PATTERN=prod_db_host
    	U_PATTERN=prod_db_user
        P_PATTERN=prod_db_password
        N_PATTERN=prod_db_name
        URL_PATTERN=prod_site_url
    else
        echo ""
        echo "Please provide a an option:"
        echo "Enter -l for local or -p for production."
        echo ""
        exit 0
    fi

    #looks for database username, database password and database name in the wp-config file
    host=`awk -F\' -v H_PATTERN="$H_PATTERN" '$0 ~ H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
    user=`awk -F\' -v U_PATTERN="$U_PATTERN" '$0 ~ U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
    pass=`awk -F\' -v P_PATTERN="$P_PATTERN" '$0 ~ P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
    db=`awk -F\' -v N_PATTERN="$N_PATTERN" '$0 ~ N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
    url=`awk -F\' -v URL_PATTERN="$URL_PATTERN" '$0 ~ N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

    d="$(date +%A-%m-%d-%Y)"
    t=$db
    the_file_name=$t-$d
    /Applications/MAMP/Library/bin/mysqldump -h$host -u$user -p$pass $db > $WHERE$DOMAIN/dumps/$the_file_name.sql

    echo ""
    echo "Database dump successful"
    echo ""
elif [ ! -z $ACTION ] && [ $ACTION == "-s" ]
then
         case $3 in
            lts )
                #staging information used to import
                F_H_PATTERN=staging_db_host
                F_U_PATTERN=staging_db_user
                F_P_PATTERN=staging_db_password
                F_N_PATTERN=staging_db_name

                #find prod url to find and replace prod url throughout the db
                F_URL_PATTERN=local_site_url

                f_host=`awk -F\' -v F_H_PATTERN="$F_H_PATTERN" '$0 ~ F_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_user=`awk -F\' -v F_U_PATTERN="$F_U_PATTERN" '$0 ~ F_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_pass=`awk -F\' -v F_P_PATTERN="$F_P_PATTERN" '$0 ~ F_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_db=`awk -F\' -v F_N_PATTERN="$F_N_PATTERN" '$0 ~ F_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                find=`awk -F\' -v F_URL_PATTERN="$F_URL_PATTERN" '$0 ~ F_URL_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

                #local information used to dump
                R_H_PATTERN=local_db_host
                R_U_PATTERN=local_db_user
                R_P_PATTERN=local_db_password
                R_N_PATTERN=local_db_name

                #local url to replace prod url throughout the db
                R_URL_PATTERN=staging_site_url

                r_host=`awk -F\' -v R_H_PATTERN="$R_H_PATTERN" '$0 ~ R_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_user=`awk -F\' -v R_U_PATTERN="$R_U_PATTERN" '$0 ~ R_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_pass=`awk -F\' -v R_P_PATTERN="$R_P_PATTERN" '$0 ~ R_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_db=`awk -F\' -v R_N_PATTERN="$R_N_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                replace=`awk -F\' -v R_URL_PATTERN="$R_URL_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                ;;
            ltp )
                #prod information used to import
                F_H_PATTERN=prod_db_host
                F_U_PATTERN=prod_db_user
                F_P_PATTERN=prod_db_password
                F_N_PATTERN=prod_db_name

                #find local url to find and replace local url throughout the db
                F_URL_PATTERN=local_site_url

                f_host=`awk -F\' -v F_H_PATTERN="$F_H_PATTERN" '$0 ~ F_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_user=`awk -F\' -v F_U_PATTERN="$F_U_PATTERN" '$0 ~ F_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_pass=`awk -F\' -v F_P_PATTERN="$F_P_PATTERN" '$0 ~ F_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_db=`awk -F\' -v F_N_PATTERN="$F_N_PATTERN" '$0 ~ F_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                find=`awk -F\' -v F_URL_PATTERN="$F_URL_PATTERN" '$0 ~ F_URL_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

                R_H_PATTERN=local_db_host
                R_U_PATTERN=local_db_user
                R_P_PATTERN=local_db_password
                R_N_PATTERN=local_db_name

                #prod url to replace local url throughout the db
                R_URL_PATTERN=prod_site_url

                r_host=`awk -F\' -v R_H_PATTERN="$R_H_PATTERN" '$0 ~ R_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_user=`awk -F\' -v R_U_PATTERN="$R_U_PATTERN" '$0 ~ R_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_pass=`awk -F\' -v R_P_PATTERN="$R_P_PATTERN" '$0 ~ R_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_db=`awk -F\' -v R_N_PATTERN="$R_N_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                replace=`awk -F\' -v R_URL_PATTERN="$R_URL_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

                ;;
            stl )
                #local information used to import
                F_H_PATTERN=local_db_host
                F_U_PATTERN=local_db_user
                F_P_PATTERN=local_db_password
                F_N_PATTERN=local_db_name

                #find staging url to find and replace staging url throughout the db
                F_URL_PATTERN=staging_site_url

                f_host=`awk -F\' -v F_H_PATTERN="$F_H_PATTERN" '$0 ~ F_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_user=`awk -F\' -v F_U_PATTERN="$F_U_PATTERN" '$0 ~ F_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_pass=`awk -F\' -v F_P_PATTERN="$F_P_PATTERN" '$0 ~ F_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_db=`awk -F\' -v F_N_PATTERN="$F_N_PATTERN" '$0 ~ F_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                find=`awk -F\' -v F_URL_PATTERN="$F_URL_PATTERN" '$0 ~ F_URL_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

                #staging information used to dump
                R_H_PATTERN=staging_db_host
                R_U_PATTERN=staging_db_user
                R_P_PATTERN=staging_db_password
                R_N_PATTERN=staging_db_name

                #local url to replace prod url throughout the db
                R_URL_PATTERN=local_site_url

                r_host=`awk -F\' -v R_H_PATTERN="$R_H_PATTERN" '$0 ~ R_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_user=`awk -F\' -v R_U_PATTERN="$R_U_PATTERN" '$0 ~ R_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_pass=`awk -F\' -v R_P_PATTERN="$R_P_PATTERN" '$0 ~ R_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_db=`awk -F\' -v R_N_PATTERN="$R_N_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                replace=`awk -F\' -v R_URL_PATTERN="$R_URL_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                ;;
            stp )
                #prod information used to import
                F_H_PATTERN=prod_db_host
                F_U_PATTERN=prod_db_user
                F_P_PATTERN=prod_db_password
                F_N_PATTERN=prod_db_name

                #find staging url to find and replace staging url throughout the db
                F_URL_PATTERN=staging_site_url

                f_host=`awk -F\' -v F_H_PATTERN="$F_H_PATTERN" '$0 ~ F_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_user=`awk -F\' -v F_U_PATTERN="$F_U_PATTERN" '$0 ~ F_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_pass=`awk -F\' -v F_P_PATTERN="$F_P_PATTERN" '$0 ~ F_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_db=`awk -F\' -v F_N_PATTERN="$F_N_PATTERN" '$0 ~ F_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                find=`awk -F\' -v F_URL_PATTERN="$F_URL_PATTERN" '$0 ~ F_URL_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

                #staging information used to dump
                R_H_PATTERN=staging_db_host
                R_U_PATTERN=staging_db_user
                R_P_PATTERN=staging_db_password
                R_N_PATTERN=staging_db_name

                #prod url to replace prod url throughout the db
                R_URL_PATTERN=prod_site_url

                r_host=`awk -F\' -v R_H_PATTERN="$R_H_PATTERN" '$0 ~ R_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_user=`awk -F\' -v R_U_PATTERN="$R_U_PATTERN" '$0 ~ R_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_pass=`awk -F\' -v R_P_PATTERN="$R_P_PATTERN" '$0 ~ R_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_db=`awk -F\' -v R_N_PATTERN="$R_N_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                replace=`awk -F\' -v R_URL_PATTERN="$R_URL_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                ;;
            ptl )
                #local information used to import
                F_H_PATTERN=local_db_host
                F_U_PATTERN=local_db_user
                F_P_PATTERN=local_db_password
                F_N_PATTERN=local_db_name

                #find prod url to find and replace prod url throughout the db
                F_URL_PATTERN=prod_site_url

                f_host=`awk -F\' -v F_H_PATTERN="$F_H_PATTERN" '$0 ~ F_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_user=`awk -F\' -v F_U_PATTERN="$F_U_PATTERN" '$0 ~ F_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_pass=`awk -F\' -v F_P_PATTERN="$F_P_PATTERN" '$0 ~ F_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_db=`awk -F\' -v F_N_PATTERN="$F_N_PATTERN" '$0 ~ F_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                find=`awk -F\' -v F_URL_PATTERN="$F_URL_PATTERN" '$0 ~ F_URL_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

                #prod information used to dump
                R_H_PATTERN=prod_db_host
                R_U_PATTERN=prod_db_user
                R_P_PATTERN=prod_db_password
                R_N_PATTERN=prod_db_name

                #local url to replace prod url throughout the db
                R_URL_PATTERN=local_site_url

                r_host=`awk -F\' -v R_H_PATTERN="$R_H_PATTERN" '$0 ~ R_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_user=`awk -F\' -v R_U_PATTERN="$R_U_PATTERN" '$0 ~ R_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_pass=`awk -F\' -v R_P_PATTERN="$R_P_PATTERN" '$0 ~ R_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_db=`awk -F\' -v R_N_PATTERN="$R_N_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                replace=`awk -F\' -v R_URL_PATTERN="$R_URL_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                ;;
            pts )
                #staging information used to import
                F_H_PATTERN=staging_db_host
                F_U_PATTERN=staging_db_user
                F_P_PATTERN=staging_db_password
                F_N_PATTERN=staging_db_name

                #find prod url to find and replace prod url throughout the db
                F_URL_PATTERN=prod_site_url

                f_host=`awk -F\' -v F_H_PATTERN="$F_H_PATTERN" '$0 ~ F_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_user=`awk -F\' -v F_U_PATTERN="$F_U_PATTERN" '$0 ~ F_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_pass=`awk -F\' -v F_P_PATTERN="$F_P_PATTERN" '$0 ~ F_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                f_db=`awk -F\' -v F_N_PATTERN="$F_N_PATTERN" '$0 ~ F_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                find=`awk -F\' -v F_URL_PATTERN="$F_URL_PATTERN" '$0 ~ F_URL_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`

                #prod information used to dump
                R_H_PATTERN=prod_db_host
                R_U_PATTERN=prod_db_user
                R_P_PATTERN=prod_db_password
                R_N_PATTERN=prod_db_name

                #staging url to replace prod url throughout the db
                R_URL_PATTERN=staging_site_url

                r_host=`awk -F\' -v R_H_PATTERN="$R_H_PATTERN" '$0 ~ R_H_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_user=`awk -F\' -v R_U_PATTERN="$R_U_PATTERN" '$0 ~ R_U_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_pass=`awk -F\' -v R_P_PATTERN="$R_P_PATTERN" '$0 ~ R_P_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                r_db=`awk -F\' -v R_N_PATTERN="$R_N_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                replace=`awk -F\' -v R_URL_PATTERN="$R_URL_PATTERN" '$0 ~ R_N_PATTERN {print $4}' "$DOMAINPATH/wp-config.php"`
                ;;
                *) echo "empty"
        esac
        d="$(date +%A-%m-%d-%Y)"
        t=$f_db
        the_file_name=$t-$d

        /Applications/MAMP/Library/bin/mysqldump -h$r_host -u$r_user -p$r_pass $r_db > $WHERE$DOMAIN/dumps/$the_file_name.sql && sed -i '' 's/$find/$replace/g' $WHERE$DOMAIN/dumps/$the_file_name.sql && /Applications/MAMP/Library/bin/mysql -h$f_host -u$f_user -p$f_pass $f_db < $WHERE$DOMAIN/dumps/$the_file_name.sql
else
         echo ""
        echo "Please choose an action:"
        echo "Enter -d for dump."
        echo ""
        exit 0
fi





